---
application:
  name: "chainsaw"
  project: "tweet-csm"
  organization: "QoveryCommunity"
  storage:
  - name: "main"
    size: "20"
    type: "fast_ssd"
    mount_point: "/mnt/main"
routers:
- name: "main-chainsaw"
  routes:
  - application_name: "chainsaw"
    paths:
    - "/*"
